"""empty message

Revision ID: d97ed18b6022
Revises: 
Create Date: 2025-03-25 07:14:29.327333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97ed18b6022'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('informations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('about_us', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ouvertures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jour', sa.String(length=50), nullable=False),
    sa.Column('heure_ouverture', sa.String(length=50), nullable=False),
    sa.Column('heure_fermeture', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reseaux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lien', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameService', sa.String(length=100), nullable=False),
    sa.Column('priceService', sa.Float(), nullable=True),
    sa.Column('imageservice', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('telephones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['informations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telephones')
    op.drop_table('users')
    op.drop_table('services')
    op.drop_table('reseaux')
    op.drop_table('ouvertures')
    op.drop_table('informations')
    # ### end Alembic commands ###
