"""empty message

Revision ID: daa7f102e42b
Revises: d97ed18b6022
Create Date: 2025-03-25 08:37:15.468020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa7f102e42b'
down_revision = 'd97ed18b6022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_us_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraph', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraph', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('why_us',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('informations', schema=None) as batch_op:
        batch_op.drop_column('about_us')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_us', sa.TEXT(), autoincrement=False, nullable=True))

    op.drop_table('why_us')
    op.drop_table('service_content')
    op.drop_table('messages')
    op.drop_table('about_us_content')
    # ### end Alembic commands ###
